In [10]:
import numpy as np

In [11]:
mp = np.random.normal(size = (4,4))
mp

array([[-0.31616409,  0.76466881,  1.29219452, -0.10890064],
       [ 0.13062644, -0.08189519,  0.59576206, -0.73791797],
       [-1.6815828 ,  0.57464179,  0.56345443, -0.80977722],
       [ 0.41419226, -0.23388328, -0.88573589, -1.59433108]])

In [13]:
pp[] = 2
mp

array([[2.        , 0.76466881, 1.29219452, 2.        ],
       [0.13062644, 2.        , 0.59576206, 2.        ],
       [2.        , 0.57464179, 0.56345443, 2.        ],
       [0.41419226, 2.        , 2.        , 2.        ]])

In [2]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

In [3]:
arr.shape

(3, 4)

In [7]:
print(arr)
arr_new = np.delete(arr, arr.shape[0]-1, axis = 0)
print(arr_new)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]


In [7]:
a = np.array([0,1])
np.tile(a,2)

array([0, 1, 0, 1])

In [8]:
a = np.array([1,2,3,4,5])
print(a)

a[2] = 10
a

[1 2 3 4 5]


array([ 1,  2, 10,  4,  5])

In [9]:
a_mul = np.array([[[1,2,3,1],
                  [4,5,6,2],
                  [7,8,9,3]],
                  [[1,2,3,1],
                  [4,5,6,2],
                  [7,8,9,3]]])

print(a_mul.shape)
print(a_mul.ndim)
print(a_mul.size)
print(a_mul.dtype)

(2, 3, 4)
3
24
int32


In [30]:
print(np.finfo(float).eps)

2.220446049250313e-16


In [14]:
a_mul.shape

(2, 3, 4)

In [18]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
np.delete(arr, 1, 1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12]])

In [29]:
arr.sum(1, keepdims = True)

array([[10],
       [26],
       [42]])

In [4]:
# a = np.array([[1,2,3],
#              [4,"Hello",6],
#              [7,8,9]], dtype = np.int32)

a = np.array([[1,2,3],
             [4,"5",6],
             [7,8,9]], dtype = np.int32)

print(a.dtype)

int32


In [5]:
print(type(a[0][0]))

<class 'numpy.int32'>


In [6]:
a = np.full((2,3,4), 9)
print(a)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [7]:
a = np.zeros((10,5,2))
print(a)

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [8]:
a = np.ones((2,3,4))
print(a)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [9]:
a = np.empty((3,3,3)) #reserves/allocates the space but does not initialized
print(a)

[[[6.23042070e-307 4.67296746e-307 1.69121096e-306]
  [9.34608432e-307 8.34441742e-308 8.90104239e-307]
  [1.33511290e-306 1.24610383e-306 1.33512173e-306]]

 [[1.06811422e-306 3.11525958e-307 1.69118108e-306]
  [8.06632139e-308 1.20160711e-306 1.69119330e-306]
  [1.29062229e-306 1.29060531e-306 6.89805151e-307]]

 [[7.56592338e-307 6.89807188e-307 2.13620807e-306]
  [1.69118787e-306 2.22522597e-306 1.33511969e-306]
  [9.45697982e-308 8.45610231e-307 3.20552953e-317]]]


In [10]:
x_values = np.arange(0, 1000, 5)
print(x_values)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [11]:
x_values = np.linspace(0,1000,4) #generates evenly spaced based on # of values
print(x_values)

[   0.          333.33333333  666.66666667 1000.        ]


In [12]:
print(np.nan) #not a number
print(np.inf) #infinity

print(np.isnan(np.nan))
print(np.isinf(np.inf))

nan
inf
True
True


In [13]:
print(np.isnan(np.sqrt(-1)))
print(np.isinf(np.array([10])/0))

True
[ True]


C:\Users\prem2\AppData\Local\Temp\ipykernel_5240\3338874168.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.isnan(np.sqrt(-1)))
C:\Users\prem2\AppData\Local\Temp\ipykernel_5240\3338874168.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.isinf(np.array([10])/0))


In [14]:
print(np.sqrt(-1))
print(np.array([10])/0)

nan
[inf]


C:\Users\prem2\AppData\Local\Temp\ipykernel_5240\1603808826.py:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))
C:\Users\prem2\AppData\Local\Temp\ipykernel_5240\1603808826.py:2: RuntimeWarning: divide by zero encountered in divide
  print(np.array([10])/0)


In [15]:
l1 = [1,2,3,4,5]
l2 = [6,7,8,9,10]

a1 = np.array(l1)
a2 = np.array(l2)

In [16]:
print(l1 * 5)
print(a1 * 5)
print(a1 + 5)

print(l1 + l2)
print(a1 + a2)

# print(l1 * l2)
print(a1 * a2)

# print(l1 / l2)
print(a1 / a2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 5 10 15 20 25]
[ 6  7  8  9 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 7  9 11 13 15]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [17]:
a1 = np.array([1,2,3])
a2 = np.array([[1],
               [2]])

In [18]:
print(a1 + a2)

[[2 3 4]
 [3 4 5]]


In [19]:
a1 = np.array([1,2,3])
a2 = np.array([[1,1],
               [2,1]])
print(a1 + a2)

ValueError: operands could not be broadcast together with shapes (3,) (2,2) 

In [ ]:
a = np.array([[1,2,3],
             [4,5,6]])
print(np.sqrt(a))

In [20]:
a = np.array([1, 2, 3])
print(np.append(a, [7,8,9])) # these functions don't change the array, they only return the result
a

[1 2 3 7 8 9]


array([1, 2, 3])

In [23]:
a = np.insert(a, 2, [4,5,6])
a

array([1, 2, 4, 5, 6, 3, 4, 5, 6, 4, 5, 6])

In [25]:
print(np.delete(a, 1))
a

[1 4 5 6 3 4 5 6 4 5 6]


array([1, 2, 4, 5, 6, 3, 4, 5, 6, 4, 5, 6])

In [31]:
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])
print(a)
print(a.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
(4, 5)


In [30]:
print(a.reshape(5,4)) # numpy function don't modify the arrayb
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [34]:
a = a.reshape(20,)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
a.resize(2,10) # resize function modifies the array
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [38]:
print(a.flatten())
print(a.ravel()) # ravel function modifies the array

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [45]:
# print(a)
a.resize(2,2,5)
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [52]:
arr = np.array([[1,2,3,4,5],
              [6,7,8,9,10]])
print(arr.transpose())
print(arr.T)

[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


In [53]:
print(a.swapaxes(0,1))

[[[ 1  2  3  4  5]
  [11 12 13 14 15]]

 [[ 6  7  8  9 10]
  [16 17 18 19 20]]]


In [54]:
a1 = np.array([[1,2,3,4,5],
               [6,7,8,9,10]])

a2 = np.array([[11,12,13,14,15],
               [16,17,18,19,20]])

In [57]:
# a = np.concatenate((a1, a2), axis=0) #axis=0 represents rows
# print(a)

a = np.concatenate((a1, a2), axis=1) #axis=1 represents columns
print(a)

[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [59]:
a = np.stack((a1,a2)) # combines to create new dimensions
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]]


In [61]:
a = np.vstack((a1,a2)) # same as concatenation on axis 0
print(a)

a = np.hstack((a1,a2)) # same as concatenation on axis 1
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 1  2  3  4  5 11 12 13 14 15]
 [ 6  7  8  9 10 16 17 18 19 20]]


In [69]:
a1 = np.array([[1,2,3,4,5,6],
               [6,7,8,9,10,11],
               [11,12,13,14,15,16],
               [16,17,18,19,20,21]])

In [80]:
print(np.split(a1, 2, axis=1))
print(np.split(a1, 3, axis=1))
# print(np.split(a, 10, axis=1))

[array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]]), array([[ 4,  5,  6],
       [ 9, 10, 11],
       [14, 15, 16],
       [19, 20, 21]])]
[array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]]), array([[ 3,  4],
       [ 8,  9],
       [13, 14],
       [18, 19]]), array([[ 5,  6],
       [10, 11],
       [15, 16],
       [20, 21]])]


In [81]:
print(a.min())
print(a.max())
print(a.mean())
print(a.std())
print(a.sum())
print(np.median(a))

1
20
10.5
5.766281297335398
210
10.5


In [85]:
number = np.random.randint(100)
print(number)

59


In [91]:
numbers = np.random.randint(100, size=(2,3,4))
print(numbers)

numbers = np.random.randint(50, 100, size=(2,3,4)) # to generate within a range
print(numbers)

numbers = np.random.randint(2, size=(2,3,4))
print(numbers)

[[[90 14  4 17]
  [14 40 89 58]
  [73 81 36 96]]

 [[63 53 17 12]
  [98 30 63 96]
  [30 92 19 68]]]
[[[99 73 84 98]
  [90 78 82 73]
  [83 82 78 62]]

 [[57 56 61 81]
  [89 85 57 80]
  [57 68 96 50]]]
[[[0 0 1 0]
  [1 0 1 0]
  [1 0 1 0]]

 [[0 0 0 0]
  [1 1 0 1]
  [0 0 1 1]]]


# Generate based on a distribution

In [93]:
numbers = np.random.binomial(10, p=0.5, size=(5,10))
print(numbers)

[[8 5 5 6 4 9 1 7 4 8]
 [5 4 8 4 4 6 5 3 4 6]
 [6 7 0 4 7 5 8 6 5 7]
 [4 5 6 6 7 4 4 3 5 5]
 [6 2 4 7 5 5 3 4 5 5]]


In [94]:
numbers = np.random.normal(loc=170, scale=15 , size=(5,10))
print(numbers)

[[168.30974964 181.06576818 177.85788456 149.42882957 182.75096002
  165.77808829 162.83830767 168.34011047 176.43430221 193.80104986]
 [166.87422985 171.51121577 162.56727042 176.46505753 163.74384228
  146.46132957 153.52956305 185.91223279 155.53152425 194.57249298]
 [152.61928302 190.18704291 149.8097859  157.12855918 181.32903
  188.13830968 161.49619813 160.53386961 171.49083557 181.5015655 ]
 [167.60995268 170.82856875 209.07583165 151.99141214 160.43028322
  193.6384598  152.92654159 155.34079721 154.36397351 165.08893858]
 [167.07846069 169.87732048 161.03690333 181.95937503 186.57275074
  155.6778713  169.05981031 156.34251061 147.56568473 161.18975103]]


In [100]:
number = np.random.choice([10,20,30,40,50], size=(5,10))
print(number)

[[30 40 50 50 10 50 50 30 10 40]
 [50 40 40 30 50 40 10 10 20 50]
 [20 20 20 20 20 10 20 50 10 50]
 [40 50 30 50 20 50 10 50 20 20]
 [10 20 10 10 40 50 40 30 40 30]]


# Exporting or importing numpy arrays

In [103]:
np.save("myarray.txt", numbers)

In [104]:
num = np.load("myarray.npy") # to save the array as npy object
print(num)

[[168.30974964 181.06576818 177.85788456 149.42882957 182.75096002
  165.77808829 162.83830767 168.34011047 176.43430221 193.80104986]
 [166.87422985 171.51121577 162.56727042 176.46505753 163.74384228
  146.46132957 153.52956305 185.91223279 155.53152425 194.57249298]
 [152.61928302 190.18704291 149.8097859  157.12855918 181.32903
  188.13830968 161.49619813 160.53386961 171.49083557 181.5015655 ]
 [167.60995268 170.82856875 209.07583165 151.99141214 160.43028322
  193.6384598  152.92654159 155.34079721 154.36397351 165.08893858]
 [167.07846069 169.87732048 161.03690333 181.95937503 186.57275074
  155.6778713  169.05981031 156.34251061 147.56568473 161.18975103]]


In [107]:
np.savetxt("myarray.csv", num, delimiter=',') # to save the array as csv file

In [108]:
numread = np.loadtxt("myarray.csv", delimiter = ',')
print(numread)

[[168.30974964 181.06576818 177.85788456 149.42882957 182.75096002
  165.77808829 162.83830767 168.34011047 176.43430221 193.80104986]
 [166.87422985 171.51121577 162.56727042 176.46505753 163.74384228
  146.46132957 153.52956305 185.91223279 155.53152425 194.57249298]
 [152.61928302 190.18704291 149.8097859  157.12855918 181.32903
  188.13830968 161.49619813 160.53386961 171.49083557 181.5015655 ]
 [167.60995268 170.82856875 209.07583165 151.99141214 160.43028322
  193.6384598  152.92654159 155.34079721 154.36397351 165.08893858]
 [167.07846069 169.87732048 161.03690333 181.95937503 186.57275074
  155.6778713  169.05981031 156.34251061 147.56568473 161.18975103]]


In [2]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [5]:
arr[arr %2 == 0] = 0

In [6]:
arr

array([[ 1,  0,  3,  0],
       [ 5,  0,  7,  0],
       [ 9,  0, 11,  0]])